#! /bin/sh

~/.config/bspwm/enforce_monitor_position HDMI-0 "^1" &

sxhkd &
compton --config /home/l7ssha/.compton &
~/.fehbg &
polybar l7ssha -r &
polybar l7ssha2 -r &

# wmname LG3D
# export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc monitor VGA-0 -d VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V

bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a vivaldi-stable desktop=^1 follow=on state=floating

bspc rule -a urxvt state=floating
bspc rule -a emacs desktop=^2 state=floating

bspc rule -a discord desktop=^6 follow=off
bspc rule -a Steam desktop=^7 follow=off state=floating
